const express = require('express')
const morgan = require('morgan')
const mongoose = require('mongoose')
const cors = require('cors')
const bodyParser = require('body-parser')
const routes = require('./Routes')
const app = express()
const port = 4000||process.env.port
app.use(morgan('dev'))
app.use(bodyParser.urlencoded({extended: false}))
app.use(express.json())
app.use(cors())
app.use(routes)

mongoose.set('strictQuery',false)
mongoose.connect('mongodb+srv://uvcomics622:CaFDcZA8lsnZqWCF@api-uvc.ahxvx8c.mongodb.net/?retryWrites=true&w=majority')
.then(() => {
    app.listen(port, () => console.log('servidor Rodando!'))
})
.catch(err => console.log(err))